# Generated by Django 4.2.4 on 2023-11-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("disc", models.TextField()),
                ("file", models.FileField(upload_to="media")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("admin_uploaded", models.BooleanField(default=False)),
            ],
        ),
    ]
