# Generated by Django 4.2.4 on 2023-12-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Coaching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("disc", models.TextField()),
            ],
        ),
    ]
