# Generated by Django 4.2.4 on 2023-12-10 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Coaching", "0002_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="disc",
            new_name="discs",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="title",
            new_name="titles",
        ),
        migrations.AddField(
            model_name="course",
            name="admin_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="files",
            field=models.FileField(
                default="default_course_file.mp4",
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
