# Generated by Django 4.2.4 on 2023-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Home_Coaching",
            "0003_rename_disc_course_discs_rename_title_course_titles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
    ]
