# Generated by Django 4.2.4 on 2023-12-10 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Coaching", "0004_course_video_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="files",
            field=models.FileField(
                default="default_course_file.mp4",
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "m4a"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
