# Generated by Django 4.2.4 on 2023-12-10 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Coaching", "0005_alter_course_files_alter_course_video_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="files",
            field=models.FileField(
                default="default_course_file.mp4",
                upload_to="media/videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
